---
title: "Data analysis"
author: "Cosmas"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F,message = F,comment = NA)
```

```{r}
rm(list=ls())
library(pacman)
p_load(readxl,tidyverse,dplyr,reshape2,ggplot2,plotly)
DataRural<-read_excel("Data/Rural-population-households-density-by-county.xlsx")
DataUrban<-read_excel("Data/Urban-population-households-density-by-county.xlsx")
DataRural['place']<-"Rural"
DataUrban['place']<-"Urban"
DataUrbanGender<-read_excel("Data/Population-in-urban-centers-by-sex-and-urban-center.xlsx")
DataFinal<-rbind(DataRural,DataUrban)


```

```{r}

library(googlesheets4)
gs4_auth()
# sheet_url <- "https://docs.google.com/spreadsheets/d/1aAwaL0fyrCGGU3QEjPA11_tnwMxmebkRY0pjNFKTF_I/edit#gid=1588788399"
# gs <- gs4_get(sheet_url)
# data <- gs4read_sheet(gs)
sheet_name <- "population distribution"
gs <- gs4_find(sheet_name)
data <- gs4read_sheet(gs)






```
```{r}
# Load the googlesheets4 package
library(googlesheets4)

# Authenticate with Google Sheets (run this only once)
gs4_auth()
```


```{r}
# Specify the name of your Google Sheet
sheet_name <- "Dataset"
gs <- gs4_find(sheet_name)
data <- read_sheet(gs)
data$Cohorts<-as.character(data$Cohorts)
data$Cohorts<-ifelse(data$Cohorts=="0-5","0-5",
                     ifelse(data$Cohorts=="1686700800","6-14",
                            ifelse(data$Cohorts=="15-35","15-35",
                                   ifelse(data$Cohorts=="36-60","36-60","61+"))))
data$Cohorts <- factor(data$Cohorts, levels = c("0-5", "6-14", "15-35", "36-60", "61+"))

data$Female<-data$Female/100000
data$Male<-data$Male/100000
library(tidyverse)

data %>% group_by(County,Cohorts) %>% summarise(Women=sum(Female),
                                         Men=sum(Male))

```

```{r}
# Create the population pyramid plot
ggplot(data, aes(x = -Female, xend = Male, y = Cohorts)) +
  geom_segment(aes(x = 0, xend = -Female, yend = Cohorts), color = "Pink", size = 2) +
  geom_segment(aes(x = 0, xend = Male, yend = Cohorts), color = "blue", size = 2) +
  labs(x = "Population Count", y = "") +
  theme_minimal() +
  scale_x_continuous(labels = abs) +
  
  theme(legend.position = "none")
ggsave("population_pyramid.png", width = 8, height = 6)






```


```{r}
# Create the population pyramid plot with space between bars
ggplot(data, aes(x = -Female, xend = Male, y = Cohorts)) +
  geom_segment(aes(x = -Female + 50, xend = Male - 50, yend = Cohorts), color = "pink", size = 2) +
  labs(x = "Population Count", y = "") +
  theme_minimal() +
  scale_x_continuous(labels = abs) +
  theme(legend.position = "none") +
 
  geom_text(aes(x = 0, label = Cohorts), hjust = 0, nudge_x = -150) +
  geom_text(aes(x = 0, label = Cohorts), hjust = 1, nudge_x = 150)



```


